# Web-only Russian translations for player-facing strings that are still empty
# in the upstream Pingus ru.po catalog pinned by patch_web_localization.py.
# Keys are matched after strip(), so harmless trailing spaces in old level data
# do not make translations disappear.

WEB_RU_FULL = {
    "Fullscreen": "Полный экран",
    "Software Cursor": "Программный курсор",
    "Renderer:": "Рендерер:",
    "You saved exactly what you needed - you made it, but\nmaybe you can do better?": "Вы спасли ровно столько, сколько было нужно — получилось,\nно, возможно, вы можете лучше?",
    "You didn't save enough, but you saved a few.  Next\ntime you might do better.": "Вы спасли не всех, кого требовалось, но несколько пингусов уцелели.\nВ следующий раз получится лучше.",
    "Only one more and you would have made it - try again!": "Не хватило всего одного пингуса — попробуйте ещё раз!",
    "Only a handful more and you would have made it - try again!": "Не хватило совсем немного пингусов — попробуйте ещё раз!",
    "???": "???",

    # Tutorial Island
    "If the way is blocked, bash away": "Если путь перекрыт — пробивайся",
    "Similar to the Digger action that you already know from previous levels, there is also an action that allows the Pingus to dig horizontally, as opposed to the vertical dig ability the Digger action provides. This new action is called Basher.": "Вы уже знакомы с Землекопом, который копает вниз. Теперь доступен Проходчик: он пробивает грунт горизонтально и помогает открыть путь вперёд.",
    "Jump for joy": "Прыгай от радости",
    "Sometimes a Pingu needs to reach a platform that is far away, but not reachable by walking. That's when the Jumper comes in handy - it allows the Pingu to make a small jump and so enables him to reach the platform.": "Иногда нужная площадка слишком далеко, чтобы дойти до неё пешком. Тогда пригодится Прыгун: он совершает небольшой прыжок и помогает перебраться через разрыв.",
    "Another action hits the street - another digging action, this time a diagonal one. It allows a Pingu to dig diagonally through ground, thus creating a path for following Pingus. The action is called Miner.": "Ещё одно действие для копания — Шахтёр. Он прокладывает тоннель по диагонали, создавая проход для остальных пингусов.",
    "Panic Island (float/bash)": "Остров паники: парашют и проходчик",
    "While the previous levels have not required much quick action from you, this one gets a bit trickier. The Pingus are coming out of two entrances in parallel and it is your job to coordinate the two groups wisely.": "Раньше спешить почти не приходилось, но теперь всё сложнее. Пингусы выходят одновременно из двух входов, и вам нужно грамотно управлять обеими группами.",
    "Jump'n Bump... and Bash...": "Прыгай, сталкивайся и пробивайся",
    "It's panic time again. The Pingus will not come out very fast, but since they turn around when they hit walls you will soon have some trouble coordinating them all. Since you only need to save 5 it should be doable, but if all else fails use the pause-mode ('p') to get an overview again.": "Снова время паниковать. Пингусы выходят не слишком быстро, но разворачиваются у стен, поэтому ими легко потерять управление. Нужно спасти только пятерых. Если станет трудно, используйте паузу, чтобы оценить ситуацию.",
    "Two groups in parallel, coordinate wisely": "Две группы — действуйте согласованно",
    "You have two groups to coordinate this time. No need to panic, since this level gives you enough time to think your actions through. No more tips this time, but good luck!": "На этот раз нужно управлять двумя группами. Времени достаточно, поэтому спокойно продумывайте действия. Подсказок больше не будет — удачи!",
    "Block'a Rock": "Останови и взорви",
    "Once again it's time to combine the things you have learned in your previous levels. Blast your way free and make sure you also keep the rest of the Pingus under control. The Blocker action will be helpful.": "Пора снова объединить уже изученные действия. Пробейте путь взрывами и не дайте остальным пингусам разбежаться. Здесь очень пригодится Блокировщик.",
    "Climb, Climber,... Boom!": "Лезь, альпинист... Бум!",
    "As you might have already figured out from previous levels, you often have to combine different actions to get the job done. Due to the lack of a Digger action in this level the Bomber needs to jump in, but how can it reach the place to bomb?": "Во многих уровнях нужно сочетать разные способности. Землекопа здесь нет, поэтому придётся использовать Подрывника. Но сначала найдите способ доставить его к нужному месту.",
    "If too high, your Pingu will die...": "Слишком высоко — пингус погибнет",
    "Teamwork is the way to the exit this time. You don't have enough Floaters to reach the exit, so just send a few and let them prepare the path for the rest.": "На этот раз поможет командная работа. Парашютистов на всех не хватит, поэтому отправьте нескольких вперёд, чтобы они подготовили безопасный путь для остальных.",
    "If no Jumper is at hand and a large hole needs to be passed, a bridge can be pretty helpful. It takes some time to build, but unlike the jumper action it allows following Pingus to reach the other end too.": "Если Прыгуна нет, а впереди большая пропасть, поможет мост. Его строительство занимает время, зато по готовому мосту смогут пройти и остальные пингусы.",
    "Climb, Climber, climb... and build a bridge": "Лезь, альпинист, и построй мост",
    "Once again you get access to a new action. The Climber action allows a Pingu to climb up straight walls, thus allowing him to reach stuff that might be too high to reach by other means.": "Вы получаете новую способность — Альпиниста. Такой пингус умеет карабкаться по отвесным стенам и добираться туда, куда иначе не попасть.",
    "Entrance high, Exit low": "Вход высоко, выход низко",
    "If you don't have enough floaters to bring all the Pingus down to the exit - you have to find other ways to guide them down. You should have learned all the stuff you need for this level in previous levels, so this shouldn't be too much of a problem for you.": "Парашютистов не хватит, чтобы безопасно спустить всех к выходу. Найдите другой путь вниз. Всё необходимое для этого вы уже изучили в предыдущих уровнях.",
    "One must prepare, the rest must follow": "Один готовит путь, остальные следуют",
    "Sometimes there are situations where you don't have a Blocker at hand to coordinate your Pingus. You'll have to find other ways to keep them under control while a single one prepares the path for the rest.": "Иногда Блокировщика нет, а пингусов всё равно нужно удержать под контролем. Найдите другой способ задержать группу, пока один пингус готовит путь остальным.",
    "Dig and float, just don't fall and smash": "Копай и парь — только не разбейся",
    "Unlike the first two levels, you have two actions available in this level. Your job is again simple: select an action at the panel on the left and apply it to the Pingus so that they will be able to reach the exit. Make sure that not too many of them die.": "Теперь вам доступны сразу два действия. Выберите нужное на панели слева и применяйте его к пингусам, чтобы провести их к выходу. Постарайтесь не потерять слишком многих.",
    "Dig, bash and other problems": "Копание, пробивание и другие проблемы",
    "The more levels you master, the more difficult they will get, but don't panic, as this one is still pretty easy. Just use the stuff that you've learned in the previous levels and you shouldn't have many problems. If you think you've reached a situation from which you can no longer solve the level, double click the armageddon button at the lower right.": "Чем дальше, тем сложнее уровни, но этот всё ещё довольно простой. Используйте уже изученные способности. Если уровень оказался в безвыходном состоянии, дважды нажмите кнопку Армагеддона справа внизу и начните заново.",
    "Solid ground can block the path": "Сталь может преградить путь",
    "As you have learned in earlier levels your Pingus can dig through basically any terrain, but there is one material which they can't penetrate: steel. These regions are marked dark grey on the level map and cannot be destroyed, so you must find a way around them.": "Пингусы могут копать почти любой грунт, но сталь им не поддаётся. Стальные участки отмечены на карте тёмно-серым и не разрушаются, поэтому придётся искать обходной путь.",

    # Halloween
    "One jump to catch them all": "Один прыжок спасёт всех",
    "The pingus have found themselves lost on their journey.  What is this mysterious place?  Smiling pumpkins, giant candlesticks, and some boiling soup below... what wizardry is this? Now, facing a deadly abyss right in front of them it's your job to save them. Can you save them from a terrible fate?": "Пингусы заблудились и попали в странное место: улыбающиеся тыквы, огромные свечи и кипящее варево внизу. Перед ними опасная пропасть. Сможете ли вы спасти их?",
    "One Thousand and One Jumps": "Тысяча и один прыжок",
    "With the exit so high above and far out of reach for a normal Pingu, what options are there? Perhaps a jumper can rescue them?  Or will he simply slow their inevitable demise? It's your job to find out, but are you good enough to save them all?": "Выход находится слишком высоко для обычного пингуса. Возможно, Прыгун сможет помочь? Найдите решение и постарайтесь спасти их всех.",
    "Boom Boom": "Бум-бум",
    "You've mastered the last challenge and now face the next. Their path to salvation seems to be cursed, but by whom? There is no time to think about it, since the next deadly challenge already awaits the Pingus. Two mighty roots block the way, but without a basher at hand to bash them away, sacrifice might be the only option...": "Предыдущее испытание позади, но путь снова перекрыт. Два огромных корня не дают пройти, а Проходчика нет. Возможно, придётся пожертвовать несколькими пингусами, чтобы спасти остальных.",
    "Full Circle": "Полный круг",
    "The exit is so close, yet out of reach. A step in the wrong direction and the Pingus will fall to a terrible fate. You must do something to help them, but is there enough time? You have to hurry and can't allow yourself any mistakes. The Pingus are counting on you!": "Выход совсем рядом, но добраться до него непросто. Один неверный шаг — и пингусы сорвутся вниз. Действуйте быстро и точно: они рассчитывают на вас.",
    "Bridgers Nightmare": "Кошмар мостостроителя",
    "Who placed this monstrous wall here?  This terrible blockade separates your Pingus from the exit. Destruction of its awful construction seems an impossibility, but perhaps the bridger can come to the rescue?  Can they build their bridges high enough to guide the group yet again safely to the exit? Or is somebody playing evil mind tricks with you?\n\nYet again the solution is your call... your gray matter is the key to the Pingus' success, so don't let yourself get confused and misguided from the true path.": "Огромная стена отделяет пингусов от выхода. Разрушить её почти невозможно, но, возможно, поможет Мостостроитель. Сможете ли вы поднять мосты достаточно высоко и вывести группу наружу?\n\nРешение снова зависит от вашей сообразительности — не дайте ложному пути сбить вас с толку.",
    "Locked up by the witch": "Заперты ведьмой",
    "Is this a prison? Blocked by solid walls all around, there doesn't seem to be a way to escape. Salvation seems impossible. But wait... the wall to the right seems weak... perhaps this is a way to escape? Or is it a false path that will lead to the Pingus' doom?\n\nThis is a risky trip, but you must take it to find out how to bring them all to freedom once again.": "Неужели это тюрьма? Вокруг прочные стены и выхода не видно. Но правая стена кажется слабее остальных. Это путь к свободе или ловушка?\n\nПридётся рискнуть и найти способ вывести всех пингусов наружу.",
    "Splatterfest": "Опасное падение",
    "This is by far the deepest pit the Pingus have yet encountered. Building a bridge across it seems obvious but that won't help since the exit is deep down in the pit itself. Pingus who try to go down the pit will just end up splattered all over the ground. You have two groups of Pingus at your disposal, can you make them work together to reach even an exit this well hidden?": "Перед пингусами самая глубокая яма из всех встреченных. Мост через неё не поможет — выход находится внизу. Простое падение смертельно. Используйте две группы вместе, чтобы безопасно добраться до спрятанного выхода.",
    "Staircase Maintenance": "Ремонт лестницы",
    "It seems we are up again against a mighty wall, and it is blocking the exit! But wait, some good soul has built a staircase around it. It seems, however, that the poor fool's efforts didn't last long, as the staircase is destroyed and full of holes. Can you fix it and make it over the wall? Yet of course you know that the right solution might not be the obvious one. But your Pingus are almost free, and they trust in your skill to guide them to safety once more. Succeed and you will have freed them once and for all from whatever evildoer that placed them in this nightmare... at least for this year.": "Снова огромная стена перекрывает выход. Рядом есть лестница, но она разрушена и полна провалов. Сможете ли вы восстановить путь и перебраться через стену? Возможно, очевидное решение не единственное. Пингусы почти свободны — проведите их к безопасности ещё раз.",

    # Halloween 2011
    "Down Into The Cave": "Вниз, в пещеру",
    "The exit is far below and the pingus are separated from it by quite a distance. The path down is riddled with gulfs, so jumping and bridging will be the primary tool to get down there. But be careful, the last few steps require some extra cleverness.": "Выход далеко внизу, а путь к нему усеян провалами. Прыжки и мосты помогут спуститься, но последние шаги потребуют особой смекалки.",
    "Round and Round": "Круг за кругом",
    "Trapped in an eternal loop one brave pingu has to break out and go on a journey in search for the exit, but he mustn't be too happy once he found it, as there is still one last challenge he must solve before being allowed to enter it, otherwise all his friends might perish.": "Один храбрый пингус должен вырваться из бесконечного круга и найти выход. Но даже найдя его, расслабляться рано: перед спасением друзей останется ещё одно испытание.",
    "Red Herring Cave": "Пещера-обманка",
    "The exit is right above the pingus heads, with a few friendly arrows pointing the way. With jumpers around the solution should be obvious. But wait, can anything you find in a dark cave be trusted or is there some more going on which might slip your view? Thinking outside the box might be required.": "Выход прямо над головами пингусов, а стрелки словно подсказывают путь. С Прыгунами решение кажется очевидным. Но можно ли доверять подсказкам в тёмной пещере? Возможно, придётся мыслить нестандартно.",
    "Group Coordination": "Согласованность групп",
    "Three groups are on their way to the exit, one of them trapped right above it, but locked into a box. None of them can make it alone, coordinate them wisely and everybody should be able to make it safely to the exit.": "К выходу движутся три группы, одна из них заперта прямо над ним. Поодиночке они не справятся — скоординируйте их действия, чтобы все добрались до выхода.",
    "Traps, Dangers and other Problems": "Ловушки, опасности и другие проблемы",
    "The path to the exit lays below, shimmering through the planks. But the fall is too high, deadly for sure. Can one pingu alone make it's way through the dangerous traps and secure the path to the exit?": "Выход виден внизу между досками, но падение с такой высоты смертельно. Сможет ли один пингус пройти через ловушки и подготовить безопасный путь остальным?",
    "Reach that Switch": "Доберись до переключателя",
    "The path to the exit is straight, flat and simple, but wait a solid door blocking the way? How can the pingus open it? Is that a switch there on the hill to the right? Might that be the solution to opening the door and freeing the pingus? But how can they reach that switch?": "Путь к выходу прямой и простой, но его перекрывает прочная дверь. Справа на холме виден переключатель — возможно, он откроет дверь. Осталось понять, как до него добраться.",
    "The Collapsed Column": "Обрушенная колонна",
    "High up above the green slime the pingus are moving from column to column, getting closer to the exit with each step, but wait, there is a second group of pingus, they are stuck. The column next to them has collapsed making getting to the exit impossible. Can you find a way around the abyss?": "Высоко над зелёной слизью пингусы идут по колоннам к выходу. Но вторая группа застряла: соседняя колонна обрушилась. Найдите способ обойти пропасть и соединить группы.",
    "Island of Doom": "Остров гибели",
    "The pingus are released close together, but split up by a solid metal column with seemingly no way to join them back up. The journey will be dangerous and some height has be crossed with the exit hidden below. With some cleverness it should be possible to join those two groups back together.": "Пингусы появляются рядом, но их разделяет прочная металлическая колонна. Впереди опасный спуск, а выход скрыт внизу. Проявите смекалку и снова соедините обе группы.",
    "Tower of Death": "Башня смерти",
    "The pingus are at the top of the tower, with no stairway around. The exit is deep down, hidden at the foot of the tower. How shall they make it down all that height with no floaters sight? A few well placed diggers should be enough to get the job done, but wait, no, their direction isn't quite right. You have to give them directions or it will be their doom.": "Пингусы на вершине башни, а выход далеко внизу. Парашютистов нет. Несколько правильно направленных Землекопов помогут спуститься, но следите за направлением — ошибка может стать роковой.",
    "The Ones": "Единицы",
    "This is the last stage the pingus have to pass during this Halloween. Two oddly familiar column are in the way. What do they mean? The two groups of pingus have to work together to make it down the columns to the exit far below.": "Последнее хэллоуинское испытание. На пути стоят две странно знакомые колонны. Две группы пингусов должны действовать вместе, чтобы спуститься по ним к выходу далеко внизу.",

    # Desert
    "Down the valley and up again": "Вниз в долину и снова наверх",
    "There is a large valley between the entrance and the exit. No bridge will be long enough to cross the valley, but can you find a way back up once you lead the Pingus down into the valley?": "Между входом и выходом лежит глубокая долина. Ни один мост не перекроет её целиком. Сможете ли вы спустить пингусов вниз, а затем найти путь обратно наверх?",
    "After their long and dangerous journey through the desert the Pingus finally reach the large pyramid, but there is still a pedestal blocking their way.": "После долгого и опасного пути через пустыню пингусы добрались до большой пирамиды, но дорогу им всё ещё преграждает массивный пьедестал.",
    "Grand Hall": "Большой зал",
    "The pingus have found themselves in the grand hall, a hall full of wonder and treasures. The exit however is high up and won't be easy to reach. Guide the pingus around the hall and maybe you will find a way.": "Пингусы оказались в огромном зале, полном чудес и сокровищ. Выход находится высоко наверху. Проведите пингусов через зал и найдите путь к нему.",
    "Pass the pedestal": "Обойти пьедестал",
    "A large pedestal is blocking the way to the exit and there aren't enough bashers available to dig it away. Can you find a way to make it past the pedestal?": "Большой пьедестал перекрывает дорогу к выходу, а Проходчиков недостаточно, чтобы убрать его. Найдите другой способ пройти дальше.",
    "The excavation of the pyramid": "Раскопки пирамиды",
    "The excavations are open to reach the pyramid for his redeeming content. Some excavations, however, is best done with two competitors. Who comes first?": "Путь к пирамиде лежит через раскопки. Некоторые участки лучше проходить сразу двумя группами. Кто доберётся первым?",
    "Catch them at the half way point": "Поймай их на полпути",
    "The Pingus are separated from the exit by large abyss. A simple bridge won't be enough to catch them safely, unless of course you find the right place to put it. Can you uncover that spot?": "Пингусов отделяет от выхода огромная пропасть. Обычного моста недостаточно — если только не поставить его в правильном месте. Сможете найти эту точку?",
    "25 Pingus free and 25 in the box": "25 пингусов на свободе и 25 в коробке",
    "Okay for the Bridger but what can I do with Digger? You should save at least one Pingu trapped in the box above the exit.": "С Мостостроителем всё понятно, но как применить Землекопа? Нужно спасти хотя бы одного пингуса, запертого в коробке над выходом.",
    "Tunnel Time": "Время тоннелей",
    "Dig a tunnel and you might make it to the exit. Digger and miners and stuff have to work together.": "Проложите тоннель к выходу. Землекопам, Шахтёрам и другим пингусам придётся работать сообща.",
    "Crawlspace": "Узкие тоннели",
    "The path to the exit is blocked and many small tunnels lead the way, but be careful some of those lead to certain death. Or is there something you can do about that and create a save passage for all the Pingus and lead them safely to the exit?": "Путь к выходу перекрыт, а вокруг множество маленьких тоннелей. Некоторые ведут прямо к гибели. Найдите безопасный маршрут и проведите всех пингусов к выходу.",
    "The Roof": "Крыша",
    "Sometimes the roofs are not good for refuge, sometimes it should be demolished! But be careful if you aren't precise enough, you might lead the Pingus straight to certain death.": "Иногда крыша не спасает, а мешает — тогда её приходится разрушать. Действуйте точно, иначе легко направить пингусов прямо в опасность.",

    # Mystery Island
    "Near can mean far": "Близко может оказаться далеко",
    "What do you do when you're going in the wrong direction ? Simple: walk into a wall. But it is easier said than done...": "Что делать, если идёшь не туда? Кажется, просто упрись в стену и развернись. Но сделать это сложнее, чем сказать...",
    "Trapped Underground": "В ловушке под землёй",
    "The penguins escaped the mad scientist, but now they were trapped deep underground. They had no food or water, so they had to move fast.": "Пингусы сбежали от безумного учёного, но оказались глубоко под землёй. Еды и воды нет, поэтому нужно двигаться быстро.",
    "The penguins stopped and stood in indecision. What was real and what was not? Flame lanced from above and a guillotine glittered in the distance. Almost all penguins must survive.": "Пингусы остановились в нерешительности: что здесь настоящее, а что иллюзия? Сверху бьёт пламя, вдали блестит гильотина. Почти все пингусы должны выжить.",
    "The Lava Pit": "Лавовая яма",
    "The penguins had defeated the mad scientist, and were walking away from his destroyed laboratory when a huge hole opened under their feet. The penguins fell into an underground cave and the only way out was across the lava pit. Luckily, it seemed someone had left some helpful signs.": "Победив безумного учёного, пингусы ушли от разрушенной лаборатории, но земля провалилась под ногами. Они оказались в подземной пещере, а единственный путь наружу ведёт через лавовую яму. К счастью, кто-то оставил подсказки.",
    "At least the experiments are over...": "По крайней мере, эксперименты закончились...",
    "The good news was that the mad scientist had tired of his experiments, the bad news was that now he was dumping them down a pit. A single flotation device was all the penguins had. Save as many as possible.": "Хорошая новость: учёному надоели эксперименты. Плохая: теперь он сбрасывает пингусов в яму. У них всего одно средство для мягкого падения — спасите как можно больше.",
    "Ghosting": "Призрачный путь",
    "The penguins came to a long pass. Acid bubbled underneath and it seemed a climber or two were needed.  Hint: slider can be used to stop the miner ability.": "Пингусы подошли к длинному проходу, под которым бурлит кислота. Похоже, понадобятся один-два Альпиниста. Подсказка: Скользящий может остановить действие Шахтёра.",
    "The Final (and surprisingly easy) Challenge": "Последнее и неожиданно лёгкое испытание",
    "The penguins had reached the end of the island. In the water was a long tree, perfect for the penguin's needs. Their journey was almost over.": "Пингусы добрались до края острова. В воде лежит длинное дерево — именно то, что нужно. Их путешествие почти завершено.",
    "Winter Wonderland": "Зимняя сказка",
    "After getting past the lava pit, the penguins walked and walked until they reached a snowed in exit. That would be relatively easy to tunnel through but how would it be possible to tunnel through solid metal?": "Минув лавовую яму, пингусы долго шли и добрались до выхода, заваленного снегом. Снег прокопать несложно, но что делать с прочным металлом?",
    "The Journey Goes On": "Путешествие продолжается",
    "And so the penguins continued on their journey, drawing ever closer to the North Pole. They had escaped the guillotine, defeated the mad scientist and got a new boat. And so this chapter in their voyage was over, but there would be other obstacles. Nothing  would stop the determined penguins from reaching their goal.": "Пингусы продолжают путь и всё ближе подходят к Северному полюсу. Они пережили гильотину, победили безумного учёного и получили новую лодку. Эта глава закончена, но впереди ещё будут препятствия. Ничто не остановит их на пути к цели.",
    "Think fast (literally)": "Думай быстро — буквально",
    "This would be simple but for one thing, there are no blockers. All the penguins must survive.": "Всё было бы просто, если бы не одно: Блокировщиков нет. И при этом должны выжить все пингусы.",
    "The penguins were sailing along happily on their makeshift boat until suddenly an island appeared. The penguins were drawn towards it and crashed, destroying their boat. Now they must find their way across this strange island.": "Пингусы спокойно плыли на самодельной лодке, когда внезапно появился остров. Течение вынесло их на берег, лодка разбилась. Теперь им нужно найти путь через этот странный остров.",

    # Alien
    "Escape from Aliens": "Побег от пришельцев",
    "Aliens invade our starship blocking entrance to the teleporter. Your crew is well trained, like you they don't panic.": "Пришельцы захватили корабль и перекрыли путь к телепорту. Ваша команда хорошо обучена и не паникует — проведите её к спасению.",
    "Escape from Aliens 2": "Побег от пришельцев 2",
    "Aliens are now closest making your escape harder. You must dig it up.": "Пришельцы подобрались ещё ближе, и побег стал сложнее. Придётся прокладывать путь копанием.",
    "Alien's nest": "Гнездо пришельцев",
    "Pingus invade the nest. Take care of jaws. What's the matrix above?": "Пингусы проникли в гнездо. Берегитесь челюстей. А что это за матрица наверху?",
    "Matrix of the death": "Матрица смерти",
    "Take a piece of paper. Now pingus have to enter the matrix of the death. This is a maze, bad ways are protect by jaws.": "Возьмите лист бумаги: пингусам предстоит войти в Матрицу смерти. Это лабиринт, а неверные пути охраняют опасные челюсти.",
    "Spy's pingus in the matrix of the death": "Пингусы-разведчики в Матрице смерти",
    "Spy's pingus have marked the location of jaws in the matrix of the death. Many died to gain that information :..( Perhaps this help. Perhaps...": "Пингусы-разведчики отметили расположение челюстей в Матрице смерти. Многие погибли, добывая эту информацию. Возможно, она поможет...",
    "Fourth dimension": "Четвёртое измерение",
    "The defenses of the aliens get stronger. Now you have to jump in the fourth dimension to win!": "Защита пришельцев становится сильнее. Теперь для победы придётся прыгнуть в четвёртое измерение!",
    "Set your watches": "Сверьте часы",
    "Cooperation in space.": "Сотрудничество в космосе.",
    "Outside In": "Снаружи внутрь",
    "Can you help the pingus escape without getting their flippers wet?": "Сможете помочь пингусам сбежать, не намочив ласты?",
    "Endless Loop": "Бесконечный цикл",
    "To the right and to the left the Pingus will face certain death and you have to save 50. Can you help them get out of this mess?": "И справа, и слева пингусов ждёт опасность, а спасти нужно 50. Помогите им выбраться из этой ловушки.",
    "Up up in the space": "Вверх, в космос",
    "What good is a pick in space? Certainly not to go to the stars.": "Какой прок от кирки в космосе? Уж точно не для полёта к звёздам.",

    # Factory Campaign
    "Jump": "Прыжок",
    "All Pingus need is to jump.... Hint: While pausing (press P key) you still can control Pingus.": "Пингусам нужно лишь прыгать. Подсказка: даже на паузе вы всё ещё можете отдавать пингусам команды.",
    "Factory": "Фабрика",
    "Finally you reached the factory. Watch out as there are many dangers. Use bombers to destroy the basement of the factory. Good luck!": "Наконец вы добрались до фабрики. Здесь много опасностей. Используйте Подрывников, чтобы разрушить основание фабрики. Удачи!",
    "The Cave": "Пещера",
    "Pingus on their way came across a huge cave. You have to lead them through. Remember that sometimes there is more than one way out. Hint: To 'unlock' blockers you can use bashers and jumpers.": "На пути пингусы встретили огромную пещеру. Проведите их через неё и помните: выход может быть не один. Подсказка: Блокировщика можно освободить Проходчиком или Прыгуном.",
    "Difficulties on the way": "Трудности в пути",
    "It looks you have encountered serious difficulties. But don't panic, Pingus are waiting for your orders, they count on you so don't fail! Hint: Miners, diggers and bashers are very important here!": "Похоже, возникли серьёзные трудности. Не паникуйте: пингусы ждут ваших приказов. Здесь особенно важны Шахтёры, Землекопы и Проходчики.",

    # Xmas 2011
    "Bomb and Double Catch": "Взрыв и двойной перехват",
    "Here you might have some time to relax. The path isn't complicated and a bit of bombing and catching of Pingus should bring you to the end without much trouble, but don't relax to much, your resources are limited, so be careful when using them.": "Здесь можно немного расслабиться. Путь несложный: несколько взрывов и правильных перехватов приведут к выходу. Но ресурсы ограничены, поэтому расходуйте их осторожно.",
    "Up, Up and Away": "Вверх и ещё выше",
    "The exit is in a weird spot here, straight above. A bridge won't get you there, but your toolset allows an alternative way. Can you figure it out?": "Выход находится прямо наверху. Обычный мост туда не приведёт, но среди ваших способностей есть другой способ. Сможете его найти?",
    "If only penguins could fly": "Если бы пингусы умели летать",
    "Bridges are kind of rare around here, so don't waste any. That aside, you shouldn't have to much trouble here, everything to do here you should have learned, but you might have to use all that knowledge at once.": "Мостов здесь мало, поэтому не тратьте их зря. Всё необходимое вы уже изучили, но теперь придётся применить сразу несколько навыков.",
    "Stairway to Heaven": "Лестница в небо",
    "Here things start to get a little complicated. Getting up to the exit is hard enough with a single Pingu, but with all of them? Impossible! But wait, who says they have to come the same way?": "Задача становится сложнее. Поднять к выходу одного пингуса уже непросто, а всех сразу кажется невозможным. Но кто сказал, что все должны идти одним путём?",
    "Misdirection Everywhere": "Ложные пути повсюду",
    "The last level for this Xmas. Looks a little complicated, right? Don't worry with all you have learned so far, you should be able to even solve this.\n\nGood Luck & a Merry Xmas 2011": "Последний рождественский уровень. Выглядит сложно? Не волнуйтесь: всех изученных навыков достаточно, чтобы решить и его.\n\nУдачи и счастливого Рождества!",
    "The Big Jump": "Большой прыжок",
    "Going in and out of the abyss with all Pingus isn't an option here, but a small group preparing the path for the others should get you across.": "Спускать в пропасть и выводить обратно всех пингусов не получится. Пусть небольшая группа подготовит путь для остальных.",
    "No Way to Stop": "Остановиться невозможно",
    "Here you don't have much time to waste. The path to the exit is clear and straight, but you don't have the time to prepare it. Can you find a way to leap ahead?": "Времени почти нет. Путь к выходу прямой и понятный, но подготовить его заранее не успеть. Найдите способ вырваться вперёд.",
    "Spiraling Away": "По спирали вниз",
    "The exit is straight below, but the path is blocked by solid steel with no way through. But the Pingus have a versatile toolset at hand, can you use it to find a way around and make it to the exit?": "Выход прямо внизу, но путь перекрыт неразрушимой сталью. Используйте способности пингусов, чтобы найти обход и добраться до выхода.",

    # Worldmap and story
    "Learn the basics": "Изучите основы",
    "The island consists of many areas that are ideal to teach the Pingus their abilities. The Pingus can learn to build bridges, climb, bash and use many other talents which they will need on their long and dangerous journey.": "На острове много мест, идеально подходящих для обучения. Здесь пингусы научатся строить мосты, карабкаться, пробивать стены и использовать другие способности, которые пригодятся в долгом путешествии.",
    "While there, you can practice your abilities in commanding and guiding the Pingus. You can also get familiar with all the abilities the Pingus provide and learn to master them, since you will need all of them on your journey around the world.": "На острове вы сможете потренироваться управлять пингусами и познакомиться со всеми их способностями. Освойте их как следует — каждая пригодится в путешествии по миру.",
    "Now after you and the Pingus have learned the basics and practiced a bit it is time to move on and begin the journey into the world. Since the ice floe with which the Pingus traveled to the Tutorial Island isn't going to hold on the whole way into the warmer climates the Pingus have to find something else to guide them on their journey.": "Теперь, когда основы изучены и немного практики позади, пора отправляться дальше. Льдина, на которой пингусы добрались до учебного острова, не выдержит путь в тёплые края, поэтому нужно найти другой транспорт.",
    "So the Pingus sit on their raft, worrying about what's to come and where to go, while floating into the sunset.\n\nTo be continued...": "Пингусы сидят на плоту и думают о том, что ждёт их впереди, пока солнце медленно садится за горизонтом.\n\nПродолжение следует...",

    # Levelsets
    "Alien by Josh Dye": "Чужие",
    "Escape from alien": "Побег от пришельцев",
    "Crystal": "Кристалл",
    "Crystaline sparkling full of danger": "Кристальный блеск, полный опасностей",
    "Eye Land": "Остров-глаз",
    "Factory Campaign": "Фабричная кампания",
    "Pingus expedition": "Экспедиция пингусов",
    "Island of Mystery": "Остров тайн",
    "Marooned on an Uncharted Isle [by Lachlan McCubbin]": "На неизведанном острове",
    "Pac-Man": "Пакман",
    "Trapped in a video game": "В ловушке видеоигры",
}

# Strings introduced by Web-only cleanup of author-bearing source labels. They
# are not present in the pinned upstream PO, so patch_web_localization appends
# them as new catalog entries.
WEB_RU_CUSTOM = {
    "Alien": "Чужие",
    "Marooned on an Uncharted Isle": "На неизведанном острове",
}
